// ── Daily rotating content pools ──────────────────────────────────────────────
// Each pool is sampled once per browser session via sessionStorage.

export const QUOTES = [
  { text: "A reader lives a thousand lives before he dies.", author: "George R.R. Martin" },
  { text: "Not all those who wander are lost.", author: "J.R.R. Tolkien" },
  { text: "There is no friend as loyal as a book.", author: "Ernest Hemingway" },
  { text: "A book is a dream that you hold in your hands.", author: "Neil Gaiman" },
  { text: "Books are a uniquely portable magic.", author: "Stephen King" },
  { text: "If you only read what everyone reads, you can only think what everyone thinks.", author: "Haruki Murakami" },
  { text: "We accept the love we think we deserve.", author: "Stephen Chbosky" },
  { text: "It does not do to dwell on dreams and forget to live.", author: "J.K. Rowling" },
  { text: "Words are our most inexhaustible source of magic.", author: "J.K. Rowling" },
  { text: "The world is a book, and those who do not travel read only one page.", author: "Saint Augustine" },
  { text: "Until I feared I would lose it, I never loved to read.", author: "Harper Lee" },
  { text: "Reading gives us someplace to go when we have to stay where we are.", author: "Mason Cooley" },
  { text: "Books are mirrors: we only see in them what we already have inside us.", author: "Carlos Ruiz Zafón" },
  { text: "No two persons ever read the same book.", author: "Edmund Wilson" },
  { text: "That's the thing about books. They let you travel without moving your feet.", author: "Jhumpa Lahiri" },
  { text: "I declare after all there is no enjoyment like reading!", author: "Jane Austen" },
  { text: "Literature is the most agreeable way of ignoring life.", author: "Fernando Pessoa" },
  { text: "Not all readers are leaders, but all leaders are readers.", author: "Harry S. Truman" },
  { text: "Think before you speak. Read before you think.", author: "Fran Lebowitz" },
  { text: "I am not afraid of storms, for I am learning to sail my ship.", author: "Louisa May Alcott" },
  { text: "All we have to decide is what to do with the time that is given us.", author: "J.R.R. Tolkien" },
  { text: "The more that you read, the more things you will know.", author: "Dr. Seuss" },
  { text: "To live is the rarest thing in the world. Most people just exist.", author: "Oscar Wilde" },
  { text: "It is never too late to be what you might have been.", author: "George Eliot" },
  { text: "A good book is an event in my life.", author: "Stendhal" },
  { text: "You can never get a cup of tea large enough or a book long enough to suit me.", author: "C.S. Lewis" },
  { text: "We read to know we are not alone.", author: "C.S. Lewis" },
  { text: "A book must be the axe for the frozen sea within us.", author: "Franz Kafka" },
  { text: "Sleep is good, he said. And books are better.", author: "George R.R. Martin" },
  { text: "Never trust anyone who has not brought a book with them.", author: "Lemony Snicket" },
  { text: "So many books, so little time.", author: "Frank Zappa" },
  { text: "You don't have to burn books to destroy a culture. Just get people to stop reading them.", author: "Ray Bradbury" },
  { text: "To read is to voyage through time.", author: "Carl Sagan" },
  { text: "A room without books is like a body without a soul.", author: "Marcus Tullius Cicero" },
  { text: "Reading is to the mind what exercise is to the body.", author: "Joseph Addison" },
  { text: "Literature adds to reality; it does not simply describe it.", author: "C.S. Lewis" },
  { text: "Good friends, good books, and a sleepy conscience: this is the ideal life.", author: "Mark Twain" },
  { text: "One glance at a book and you hear the voice of another person, perhaps someone dead for 1,000 years.", author: "Italo Calvino" },
  { text: "There are two motives for reading: enjoyment, and boasting about it.", author: "Bertrand Russell" },
  { text: "Always read something that will make you look good if you die in the middle of it.", author: "P.J. O'Rourke" },
  { text: "The books that the world calls immoral are books that show the world its own shame.", author: "Oscar Wilde" },
  { text: "A truly great book should be read in youth, again in maturity, and once more in old age.", author: "Robertson Davies" },
  { text: "Every book you've ever read is just a different arrangement of 26 letters.", author: "Unknown" },
  { text: "I took a speed reading course and read War and Peace in twenty minutes. It involves Russia.", author: "Woody Allen" },
  { text: "The person who deserves most pity is a lonesome one on a rainy day who doesn't know how to read.", author: "Benjamin Franklin" },
  { text: "A book is a loaded gun in the house next door.", author: "Ray Bradbury, Fahrenheit 451" },
  { text: "Not I, nor anyone else can travel that road for you. You must travel it by yourself.", author: "Walt Whitman" },
  { text: "It's the possibility of having a dream come true that makes life interesting.", author: "Paulo Coelho" },
  { text: "The magic is only in what books say, how they stitched the patches of the universe together.", author: "Ray Bradbury" },
  { text: "I took a deep breath and listened to the old brag of my heart: I am, I am, I am.", author: "Sylvia Plath" },
];

export const WORDS = [
  { word: "Bibliophile", type: "noun", definition: "A person who collects or has a great love of books.", example: "Every bibliophile knows the struggle of too many books and too little shelf space." },
  { word: "Tsundoku", type: "noun (Japanese)", definition: "The act of buying books and letting them pile up unread.", example: "Her tsundoku was evident from the towering stacks on every surface of her flat." },
  { word: "Petrichor", type: "noun", definition: "The pleasant earthy smell produced when rain falls on dry ground.", example: "The petrichor drifting through the open window made the perfect reading atmosphere." },
  { word: "Sonder", type: "noun", definition: "The realisation that each passerby has a life as vivid and complex as your own.", example: "Reading literary fiction filled her with sonder for the strangers she passed each day." },
  { word: "Palimpsest", type: "noun", definition: "A manuscript where original writing was scraped off and written over, leaving traces.", example: "The old journal was like a palimpsest of her former self — old thoughts still visible beneath the new." },
  { word: "Lacuna", type: "noun", definition: "A missing portion in a text or argument; a gap or blank.", example: "The damaged scroll had several lacunae that left scholars debating its true meaning." },
  { word: "Hiraeth", type: "noun (Welsh)", definition: "A deep longing for a home or era that may no longer exist, or never did.", example: "Flipping through old photo albums always stirred in him an inexplicable hiraeth." },
  { word: "Mellifluous", type: "adjective", definition: "Sweet or musical; pleasant to hear.", example: "The narrator's mellifluous voice made the audiobook impossible to pause." },
  { word: "Verisimilitude", type: "noun", definition: "The appearance of being true or real within a fictional work.", example: "The novel's verisimilitude was so strong that readers often forgot it was fiction." },
  { word: "Catharsis", type: "noun", definition: "The release of strong or repressed emotions through art or drama.", example: "She finally wept at the novel's end — a profound and much-needed catharsis." },
  { word: "Dénouement", type: "noun (French)", definition: "The final part of a story in which the conflict is resolved.", example: "The dénouement of the thriller was so unexpected she had to reread it twice." },
  { word: "Epistolary", type: "adjective", definition: "Relating to a literary work written in the form of letters or diary entries.", example: "Dracula is partly epistolary, told through journals, letters, and newspaper clippings." },
  { word: "Anachronism", type: "noun", definition: "Something out of its proper historical time period.", example: "The appearance of a smartphone in a Victorian novel was a jarring anachronism." },
  { word: "Hubris", type: "noun", definition: "Excessive pride or self-confidence, especially in a tragic hero.", example: "It was the king's hubris — his absolute certainty of victory — that brought about his downfall." },
  { word: "Soliloquy", type: "noun", definition: "Speaking one's thoughts aloud when alone or unaware of listeners.", example: "Hamlet's 'To be or not to be' is the most famous soliloquy in all of English literature." },
  { word: "Apocryphal", type: "adjective", definition: "Of doubtful authenticity, though widely circulated as true.", example: "The story of Shakespeare writing his plays in a pub is almost certainly apocryphal." },
  { word: "Bildungsroman", type: "noun (German)", definition: "A novel focused on the moral and psychological growth of the protagonist.", example: "The Catcher in the Rye is a classic American bildungsroman." },
  { word: "Limerence", type: "noun", definition: "A state of obsessive, involuntary infatuation with another person.", example: "The protagonist's limerence consumed every chapter of the novel's first act." },
  { word: "Ephemeral", type: "adjective", definition: "Lasting for a very short time; transient.", example: "The story explored the ephemeral beauty of a single summer that changed everything." },
  { word: "Elegy", type: "noun", definition: "A mournful poem or piece of writing; a lament for the dead or lost.", example: "Her final novel read like an elegy for a childhood home long since demolished." },
  { word: "Pastiche", type: "noun", definition: "A work that imitates the style of another artist, era, or genre.", example: "The novel was an affectionate pastiche of Victorian gothic literature." },
  { word: "Serendipity", type: "noun", definition: "The occurrence of fortunate discoveries entirely by accident.", example: "Finding a first-edition Hemingway at a car boot sale was sheer serendipity." },
  { word: "Ennui", type: "noun (French)", definition: "A feeling of listlessness and dissatisfaction from lack of occupation.", example: "The idle aristocrat in the novel was consumed by a profound, suffocating ennui." },
  { word: "Foible", type: "noun", definition: "A minor weakness or failing in someone's character.", example: "Each character's foibles were what made the novel so endearingly human." },
  { word: "Dystopia", type: "noun", definition: "An imagined society that is frightening or deeply undesirable.", example: "From 1984 to The Handmaid's Tale, dystopia is one of fiction's richest and most urgent genres." },
  { word: "Cadence", type: "noun", definition: "The rhythmic flow of a sequence of sounds or words in language.", example: "Cormac McCarthy's prose has an unmistakable, biblical cadence." },
  { word: "Allegory", type: "noun", definition: "A story with a hidden meaning, typically moral or political.", example: "Animal Farm is a thinly veiled allegory for the Russian Revolution and Stalinist dictatorship." },
  { word: "Saudade", type: "noun (Portuguese)", definition: "A deep nostalgic longing for something or someone beloved that is absent or lost.", example: "The Portuguese novels she adored were saturated with saudade — beautiful and aching." },
  { word: "Liminal", type: "adjective", definition: "Relating to a transitional or in-between state; on a threshold.", example: "The novel takes place in a liminal space between childhood and adulthood." },
  { word: "Ineffable", type: "adjective", definition: "Too great or extreme to be expressed in words.", example: "The final page left her with an ineffable feeling she would carry for days." },
  { word: "Redolent", type: "adjective", definition: "Strongly reminiscent of something; having a pleasant smell.", example: "The dusty library was redolent of old paper and forgotten adventures." },
  { word: "Quixotic", type: "adjective", definition: "Exceedingly idealistic; unrealistic and impractical.", example: "His quixotic quest to read every Booker Prize winner in a single year was admirable, if doomed." },
  { word: "Susurrus", type: "noun", definition: "A whispering or murmuring sound.", example: "The susurrus of turning pages in a silent library was the most peaceful sound she knew." },
  { word: "Metafiction", type: "noun", definition: "Fiction that self-consciously addresses the devices of fiction itself.", example: "Italo Calvino's If on a winter's night a traveler is a masterpiece of playful metafiction." },
  { word: "Nadir", type: "noun", definition: "The lowest point; the opposite of zenith.", example: "Chapter twelve marked the protagonist's nadir before her slow, hard-won redemption." },
  { word: "Euphony", type: "noun", definition: "The quality of being pleasing to the ear; beautiful sound in language.", example: "The poem's euphony made it feel almost like music when read aloud." },
  { word: "Bathos", type: "noun", definition: "An abrupt, jarring transition from the serious to the trivial; unintentional anticlimax.", example: "The epic battle scene was ruined by bathos when the hero tripped over a bucket." },
  { word: "Crepuscular", type: "adjective", definition: "Relating to twilight; dim or indistinct.", example: "The novel's crepuscular mood suited its themes of endings and half-forgotten things." },
  { word: "Aphorism", type: "noun", definition: "A pithy observation containing a general truth.", example: "'Show, don't tell' is the aphorism every writing tutor inevitably reaches for." },
  { word: "Hyperbole", type: "noun", definition: "Exaggerated statements not meant to be taken literally.", example: "'I've read this book a thousand times' is hyperbole — but it captures the feeling perfectly." },
  { word: "Lexicon", type: "noun", definition: "The vocabulary of a person, language, or field of knowledge.", example: "Shakespeare is said to have added over 1,700 words to the English lexicon." },
  { word: "Wabi-sabi", type: "noun (Japanese)", definition: "The beauty found in imperfection, impermanence, and incompleteness.", example: "The novel's weathered, imperfect protagonist embodied true wabi-sabi." },
  { word: "Cogitate", type: "verb", definition: "To think deeply about something; to ponder with care.", example: "He would cogitate for hours over a single sentence before committing it to the page." },
  { word: "Syzygy", type: "noun", definition: "A pair of connected or corresponding things; alignment of three celestial bodies.", example: "The author used a syzygy of parallel characters to explore opposing philosophies of justice." },
  { word: "Prosody", type: "noun", definition: "The patterns of rhythm, stress, and intonation in language, especially poetry.", example: "The professor's lecture on the prosody of Shakespeare's sonnets made the room fall silent." },
  { word: "Ambivalence", type: "noun", definition: "The state of having mixed or contradictory feelings about something.", example: "The narrator's ambivalence about leaving home is the quiet emotional engine of the whole book." },
  { word: "Panegyric", type: "noun", definition: "A public speech or published text in praise of someone or something.", example: "The obituary read more like a panegyric than an honest account of the author's complicated life." },
  { word: "Penultimate", type: "adjective", definition: "Second to last in a series.", example: "The penultimate chapter delivered the twist that recontextualised everything before it." },
  { word: "Sophrosyne", type: "noun (Greek)", definition: "A healthy, balanced state of mind: self-control, moderation, and wisdom.", example: "The stoic philosopher's letters were a model of sophrosyne — measured, clear, and free from excess." },
  { word: "Catachresis", type: "noun", definition: "The strained or incorrect use of a word, sometimes for dramatic effect.", example: "Calling ambition 'the mind's ladder' is a catachresis — but a memorable one." },
];

export const DID_YOU_KNOW = [
  { fact: "J.K. Rowling's Harry Potter was rejected by 12 different publishers before Bloomsbury took a chance on it in 1997." },
  { fact: "Agatha Christie is the best-selling fiction writer of all time, with over 2 billion books sold — second only to the Bible and Shakespeare." },
  { fact: "Leo Tolstoy's wife, Sofia, hand-copied the entire manuscript of War and Peace — all 580,000 words — eight times." },
  { fact: "William Shakespeare is credited with inventing over 1,700 English words, including 'bedroom', 'lonely', 'generous', and 'obscene'." },
  { fact: "J.R.R. Tolkien created at least 14 complete fictional languages for Middle-earth, including Quenya and Sindarin." },
  { fact: "Stephen King threw the first draft of Carrie in the bin. His wife rescued it and convinced him to finish it — it became his first published novel." },
  { fact: "Mary Shelley wrote Frankenstein at just 18 years old, during a ghost story competition on a stormy night in Switzerland." },
  { fact: "George Orwell's 1984 was originally titled 'The Last Man in Europe'. The publisher changed it." },
  { fact: "Sherlock Holmes never actually says 'Elementary, my dear Watson' anywhere in Conan Doyle's original stories." },
  { fact: "The original Winnie-the-Pooh stuffed toys that inspired A.A. Milne are kept in a display case at the New York Public Library." },
  { fact: "Dr. Seuss wrote Green Eggs and Ham using only 50 different words after losing a bet with his editor." },
  { fact: "Anne Frank's diary was rejected by 15 publishers before finally being accepted and published in 1947." },
  { fact: "F. Scott Fitzgerald's The Great Gatsby sold fewer than 25,000 copies in his lifetime. He considered it a flop. Today it sells 500,000 copies a year." },
  { fact: "Roald Dahl wrote all his books in a small hut at the bottom of his garden, sitting in a battered armchair with a board across his lap." },
  { fact: "Lewis Carroll wrote Alice's Adventures in Wonderland specifically to entertain one child — Alice Liddell, daughter of an Oxford colleague." },
  { fact: "There are more public libraries in the United States than McDonald's restaurants." },
  { fact: "The Harry Potter series has been translated into 85 languages, including Latin and Ancient Greek." },
  { fact: "Herman Melville's Moby-Dick was a commercial disaster when first published. It sold fewer than 3,000 copies in his lifetime." },
  { fact: "The first book typed on a typewriter submitted as a manuscript was The Adventures of Tom Sawyer by Mark Twain, in 1876." },
  { fact: "Voltaire reportedly wrote Candide in just three days. It has never gone out of print since 1759." },
  { fact: "Marcel Proust wrote In Search of Lost Time almost entirely in a cork-lined bedroom, specifically to block out noise." },
  { fact: "The Library of Congress in Washington D.C. is the largest library in the world, housing over 170 million items." },
  { fact: "The name 'Wendy' was effectively invented by J.M. Barrie for the character in Peter Pan — it was almost non-existent as a name before 1904." },
  { fact: "Don Quixote by Miguel de Cervantes is often cited as the world's best-selling novel with an estimated 500 million copies sold." },
  { fact: "The oldest known written story is The Epic of Gilgamesh, dating back to around 2100 BCE in ancient Mesopotamia." },
  { fact: "Bram Stoker researched Dracula for 7 years, but never actually visited Transylvania." },
  { fact: "The term 'Catch-22' entered the English language from Joseph Heller's 1961 novel. He originally called it 'Catch-18'." },
  { fact: "Charles Dickens always slept facing north, believing it improved his writing and creativity." },
  { fact: "Gabriel García Márquez wrote One Hundred Years of Solitude in 18 months while his family nearly went bankrupt." },
  { fact: "J.D. Salinger published only one novel in his lifetime — The Catcher in the Rye — yet continued writing privately until his death." },
  { fact: "Agatha Christie disappeared for 11 days in 1926. She was found 200 miles from home under a false name. She never explained what happened." },
  { fact: "Jane Austen published all her novels anonymously, credited only as 'A Lady'. Her identity was widely known only after her death." },
  { fact: "The paperback book was invented in 1935 by Allen Lane, who got the idea while stranded at a train station with nothing good to read." },
  { fact: "Tolkien and C.S. Lewis were close friends and colleagues at Oxford. Lewis credited Tolkien with helping lead him back to Christianity." },
  { fact: "Franz Kafka asked his friend Max Brod to burn all his unpublished manuscripts after his death. Brod refused — and published them instead." },
  { fact: "Virginia Woolf wrote her novels standing up at a writing desk, averaging just 500 words a day." },
  { fact: "Dan Brown wrote The Da Vinci Code working from 4 AM every day, keeping an hourglass on his desk and doing push-ups every time it ran out." },
  { fact: "The Bible is estimated to have sold 5–7 billion copies — the best-selling book of all time by an enormous margin." },
  { fact: "The phrase 'It was a dark and stormy night' — universally mocked as purple prose — comes from the 1830 novel Paul Clifford by Edward Bulwer-Lytton." },
  { fact: "In Hermione Granger's early drafts, Rowling nearly named her 'Hermione Puckle' before settling on Granger." },
  { fact: "Isaac Asimov wrote or edited over 500 books, covering almost every category in the Dewey Decimal System." },
  { fact: "The word 'serendipity' was coined by Horace Walpole in 1754, inspired by a Persian fairy tale called The Three Princes of Serendip." },
  { fact: "Long John Silver in Treasure Island was based on Stevenson's real-life friend, poet W.E. Henley, who had lost a leg to tuberculosis." },
  { fact: "Random House was founded in 1927. Co-founder Bennett Cerf said the name came from their intention to publish 'a few books at random'." },
  { fact: "The character of Dracula was partly inspired by a real 15th-century Romanian ruler, Vlad III, known as Vlad the Impaler." },
  { fact: "Ernest Hemingway developed his minimalist style partly because he was paid by the word as a journalist — and he despised waste." },
  { fact: "The first Gutenberg Bible was printed around 1455. Only 49 complete or near-complete copies survive today." },
  { fact: "Lewis Carroll (Charles Dodgson) was a mathematics lecturer at Oxford who suffered from a stutter — Alice was partly based on his own shyness." },
  { fact: "Lolita by Vladimir Nabokov was rejected by four American publishers before being published in Paris in 1955." },
  { fact: "Stephen King has published over 65 novels. He writes 2,000 words every single day — including his birthday and Christmas." },
];

export const TRIVIA = [
  { q: "What is the best-selling novel of all time (excluding the Bible)?", a: "Don Quixote by Miguel de Cervantes", detail: "With an estimated 500 million copies sold since its first publication in 1605." },
  { q: "In which Shakespeare play does 'To be or not to be' appear?", a: "Hamlet", detail: "Act 3, Scene 1. One of the most quoted lines in all of English literature." },
  { q: "Who wrote 1984 and Animal Farm?", a: "George Orwell (real name: Eric Arthur Blair)", detail: "Both published in the 1940s and still among the most widely read political novels ever written." },
  { q: "How many books are in J.K. Rowling's original Harry Potter series?", a: "7 books", detail: "From The Philosopher's Stone (1997) to The Deathly Hallows (2007)." },
  { q: "Who created the fictional detective Sherlock Holmes?", a: "Arthur Conan Doyle", detail: "Holmes first appeared in A Study in Scarlet (1887) and is arguably the most famous fictional detective ever." },
  { q: "Who wrote The Lord of the Rings?", a: "J.R.R. Tolkien", detail: "Published in three volumes in 1954–1955. Tolkien also wrote The Hobbit and The Silmarillion." },
  { q: "What is Mr. Darcy's first name in Pride and Prejudice?", a: "Fitzwilliam", detail: "Jane Austen published the novel in 1813. Darcy's full name appears very rarely in the text." },
  { q: "Who wrote The Great Gatsby?", a: "F. Scott Fitzgerald", detail: "Published in 1925. It sold poorly in Fitzgerald's lifetime but became a cornerstone of American literature." },
  { q: "Which novel features 'Big Brother' and 'doublethink'?", a: "1984 by George Orwell", detail: "Published in 1949, it coined numerous terms that have permanently entered everyday language." },
  { q: "Which novel begins: 'It was the best of times, it was the worst of times'?", a: "A Tale of Two Cities by Charles Dickens", detail: "Set during the French Revolution, published in 1859. One of the best-selling novels of all time." },
  { q: "Who wrote the Chronicles of Narnia?", a: "C.S. Lewis", detail: "The seven-book series, starting with The Lion, the Witch and the Wardrobe, was published 1950–1956." },
  { q: "What is the name of the great white whale in Moby-Dick?", a: "Moby Dick", detail: "Herman Melville's 1851 novel — a commercial failure in his lifetime, now considered a masterpiece." },
  { q: "In which country is The Kite Runner set?", a: "Afghanistan", detail: "Written by Khaled Hosseini, published in 2003. It became a global bestseller." },
  { q: "Who wrote Frankenstein?", a: "Mary Shelley", detail: "She wrote it at 18 during a ghost story competition in Geneva in 1816. Published anonymously in 1818." },
  { q: "What is the subtitle of Mary Shelley's Frankenstein?", a: "The Modern Prometheus", detail: "It references the Greek titan Prometheus, who stole fire from the gods to give to humanity." },
  { q: "Who wrote Brave New World?", a: "Aldous Huxley", detail: "Published in 1932, it depicts a scientifically advanced but deeply dehumanised future society." },
  { q: "What is the name of the orphan raised by wolves in The Jungle Book?", a: "Mowgli", detail: "From Rudyard Kipling's 1894 novel — Mowgli is raised by wolves in the jungles of India." },
  { q: "Who wrote The Catcher in the Rye?", a: "J.D. Salinger", detail: "Published in 1951. Salinger published almost nothing else and became a total recluse." },
  { q: "In The Hitchhiker's Guide to the Galaxy, what is the answer to life, the universe, and everything?", a: "42", detail: "Calculated by the supercomputer Deep Thought after 7.5 million years of processing." },
  { q: "Who wrote Crime and Punishment?", a: "Fyodor Dostoevsky", detail: "Published in 1866 — it follows Raskolnikov, a student who murders a pawnbroker and wrestles with guilt." },
  { q: "In which Dickens novel does Ebenezer Scrooge appear?", a: "A Christmas Carol (1843)", detail: "Scrooge is visited by the ghosts of Christmas Past, Present, and Yet to Come." },
  { q: "Who is Frodo's loyal gardener in The Lord of the Rings?", a: "Samwise Gamgee", detail: "Sam is often called the true hero of the story — he literally carries Frodo up Mount Doom." },
  { q: "Who wrote One Hundred Years of Solitude?", a: "Gabriel García Márquez", detail: "The 1967 Colombian novel is the cornerstone of magic realism. He won the Nobel Prize in 1982." },
  { q: "Who is the author of the Discworld series?", a: "Terry Pratchett", detail: "He wrote 41 Discworld novels between 1983 and 2015. The series has sold over 85 million copies." },
  { q: "Who is the narrator of To Kill a Mockingbird?", a: "Scout Finch (Jean Louise Finch)", detail: "Harper Lee's 1960 novel is told from young Scout's perspective growing up in 1930s Alabama." },
  { q: "What is the famous first line of Moby-Dick?", a: "'Call me Ishmael.'", detail: "Three of the most famous words in American literature — deceptively simple and instantly iconic." },
  { q: "Who wrote Anna Karenina?", a: "Leo Tolstoy", detail: "Published in 1878. It is frequently described as the greatest novel ever written." },
  { q: "What is the name of the villain in The Lion, the Witch and the Wardrobe?", a: "The White Witch (Jadis)", detail: "She has cursed Narnia with eternal winter — but never Christmas." },
  { q: "Who wrote The Handmaid's Tale?", a: "Margaret Atwood", detail: "Published in 1985. The sequel, The Testaments, won the Booker Prize in 2019." },
  { q: "Who wrote Dune?", a: "Frank Herbert", detail: "Published in 1965. Dune is the best-selling science fiction novel of all time." },
  { q: "In which Shakespeare play does the villain Iago appear?", a: "Othello", detail: "Iago is one of literature's most infamous villains — calculating, envious, and utterly ruthless." },
  { q: "Who wrote The Picture of Dorian Gray?", a: "Oscar Wilde", detail: "Published in 1890. A young man's portrait ages in his place while he remains eternally young." },
  { q: "What award did Kazuo Ishiguro win for The Remains of the Day?", a: "The Booker Prize (1989)", detail: "Ishiguro later won the Nobel Prize in Literature in 2017." },
  { q: "What is the name of Bilbo Baggins' home in The Hobbit?", a: "Bag End", detail: "A cosy hobbit-hole under Bag Hill in the Shire. Later inherited by Frodo." },
  { q: "Who wrote Beloved?", a: "Toni Morrison", detail: "Published in 1987. It won the Pulitzer Prize and helped earn Morrison the Nobel Prize in 1993." },
  { q: "What language was Don Quixote originally written in?", a: "Spanish (Castilian)", detail: "By Miguel de Cervantes, published in two parts in 1605 and 1615. Often called the first modern novel." },
  { q: "Who wrote The Canterbury Tales?", a: "Geoffrey Chaucer", detail: "Written in the late 14th century, it remains one of the greatest works of Middle English literature." },
  { q: "In Rebecca by Daphne du Maurier, what is the narrator's name?", a: "She is never named in the novel.", detail: "Her namelessness is one of the novel's most chilling and deliberate literary devices." },
  { q: "Who wrote The Brothers Karamazov?", a: "Fyodor Dostoevsky", detail: "His final and longest novel, published in 1880. Many consider it the single greatest novel ever written." },
  { q: "Which Hemingway novel is set during the Spanish Civil War?", a: "For Whom the Bell Tolls (1940)", detail: "It follows American Robert Jordan fighting alongside Spanish guerrilla fighters." },
  { q: "Who wrote Middlemarch?", a: "George Eliot (real name: Mary Ann Evans)", detail: "Virginia Woolf called it 'one of the few English novels written for grown-up people'." },
  { q: "What is the name of the island in Lord of the Flies — and why?", a: "It is never named.", detail: "William Golding's 1954 novel deliberately leaves the island nameless, making its horror feel universal." },
  { q: "What does the title 'Fahrenheit 451' refer to?", a: "The temperature at which paper ignites and burns.", detail: "Ray Bradbury's 1953 novel depicts a dystopia where books are outlawed and firemen burn them." },
  { q: "Who wrote Lolita?", a: "Vladimir Nabokov", detail: "Published in 1955. Controversial and critically acclaimed — Nabokov wrote it first in English, not his native Russian." },
  { q: "Which novel opens with 'Happy families are all alike; every unhappy family is unhappy in its own way'?", a: "Anna Karenina by Leo Tolstoy", detail: "One of the most famous opening lines in world literature." },
  { q: "Who wrote The Old Man and the Sea?", a: "Ernest Hemingway", detail: "Published in 1952. It won the Pulitzer Prize in 1953 and contributed to his Nobel Prize in Literature in 1954." },
  { q: "In which novel would you find the character Heathcliff?", a: "Wuthering Heights by Emily Brontë (1847)", detail: "Heathcliff is one of English literature's most brooding and complex romantic anti-heroes." },
  { q: "Who wrote The Count of Monte Cristo?", a: "Alexandre Dumas", detail: "Published in serialised form in 1844–1846. An epic adventure of imprisonment, escape, and revenge." },
  { q: "What is the name of the fictional African kingdom in Black Panther's comics?", a: "Wakanda", detail: "Created by Stan Lee and Jack Kirby in the Marvel comics, first appearing in Fantastic Four #52 (1966)." },
  { q: "Who wrote Sense and Sensibility?", a: "Jane Austen", detail: "Published in 1811 — her first published novel, released anonymously as 'By a Lady'." },
  { q: "In which novel does the character Atticus Finch appear?", a: "To Kill a Mockingbird by Harper Lee (1960)", detail: "Atticus, a lawyer defending a Black man in the American South, is one of literature's great moral heroes." },
];
